#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""CLI command for shell tab-completion — registered on main CLI group."""

import click


_SOURCE_MAP = {"bash": "bash_source", "zsh": "zsh_source", "fish": "fish_source"}
_RC_MAP = {
    "bash": "~/.bashrc",
    "zsh": "~/.zshrc",
    "fish": "~/.config/fish/completions/scitex-dev.fish",
}


def _generate_script(shell: str) -> str:
    import os
    import subprocess

    env = os.environ.copy()
    env["_SCITEX_DEV_COMPLETE"] = _SOURCE_MAP[shell]
    result = subprocess.run(["scitex-dev"], capture_output=True, text=True, env=env)
    script = result.stdout.strip()
    if not script:
        raise click.ClickException(f"Failed to generate {shell} completion script.")
    return script


def _eval_line(shell: str) -> str:
    """The exact line that gets appended to the user's rc file."""
    marker = "# scitex-dev tab completion"
    return f'eval "$(_SCITEX_DEV_COMPLETE={_SOURCE_MAP[shell]} scitex-dev)"  {marker}'


def register_completion_command(main_group):
    """Register tab-completion commands on the main CLI."""

    @main_group.command(
        "completion",
        hidden=True,
        context_settings={"ignore_unknown_options": True, "allow_extra_args": True},
    )
    @click.pass_context
    def completion_deprecated(ctx):
        """(deprecated) Use `install-tab-completion`."""
        click.echo(
            "error: `scitex-dev completion` was renamed.\n"
            "Re-run with:\n"
            "  scitex-dev install-tab-completion [--shell bash|zsh|fish] [--dry-run]",
            err=True,
        )
        ctx.exit(2)

    @main_group.command(
        "print-tab-completion",
        hidden=True,
        deprecated=True,
    )
    @click.option(
        "--shell",
        type=click.Choice(["bash", "zsh", "fish"]),
        default="bash",
        help="Target shell. Default: bash.",
    )
    def print_tab_completion(shell):
        """(deprecated) Use `install-tab-completion --dry-run` instead.

        Will be removed in 0.11.0.
        """
        click.echo(
            "warning: `print-tab-completion` is deprecated; use "
            "`install-tab-completion --dry-run` to inspect the eval line, "
            'or `eval "$(_SCITEX_DEV_COMPLETE=bash_source scitex-dev)"` '
            "to activate without writing to rc.",
            err=True,
        )
        click.echo(_generate_script(shell))

    @main_group.command("install-tab-completion")
    @click.option(
        "--shell",
        type=click.Choice(["bash", "zsh", "fish"]),
        default="bash",
        help="Target shell. Default: bash.",
    )
    @click.option(
        "--dry-run",
        is_flag=True,
        help="Print the eval line and target rc file without writing.",
    )
    def install_tab_completion(shell, dry_run):
        """Append a one-line eval to the shell's rc file (idempotent).

        The line evaluates the completion script generated by Click whenever
        a new shell starts:

        \b
            eval "$(_SCITEX_DEV_COMPLETE=bash_source scitex-dev)"  # bash → ~/.bashrc
            eval "$(_SCITEX_DEV_COMPLETE=zsh_source scitex-dev)"   # zsh  → ~/.zshrc
            (fish is written to ~/.config/fish/completions/scitex-dev.fish)

        \b
        Examples:
          scitex-dev install-tab-completion               # → ~/.bashrc
          scitex-dev install-tab-completion --shell zsh   # → ~/.zshrc
          scitex-dev install-tab-completion --dry-run     # preview, don't write

        \b
        Activate in the current shell after install:
          source ~/.bashrc

        \b
        For one-off activation without persisting to rc:
          eval "$(_SCITEX_DEV_COMPLETE=bash_source scitex-dev)"
        """
        import os

        rc_path = os.path.expanduser(_RC_MAP[shell])
        line = _eval_line(shell)
        marker = "# scitex-dev tab completion"

        if dry_run:
            click.echo(f"Would append to {rc_path}:")
            click.echo(f"  {line}")
            return

        if os.path.isfile(rc_path):
            with open(rc_path) as f:
                if marker in f.read():
                    click.echo(f"Tab completion already installed in {rc_path}")
                    return
        with open(rc_path, "a") as f:
            f.write(f"\n{line}\n")
        click.echo(f"Tab completion installed in {rc_path}")
        click.echo(f"Run: source {rc_path}")
