"""Constants for the project-structure auditor.

Split out of `_audit.py` (issue #103) — pure refactor, no behaviour change.
Re-exported from `_audit` for backward compatibility.
"""

from __future__ import annotations

import re
from pathlib import Path


# Test-name patterns: split into private (test__name.py) and public (test_name.py).
# The leading-underscore in the source becomes a double underscore in the test.
# Captured group allows optional extra leading underscores so dunder sources
# like `__main__.py` (test `test___main__.py`) are recognised as having a
# valid src mirror.
_PRIVATE_TEST_RE = re.compile(r"^test__(_*[A-Za-z0-9][A-Za-z0-9_]*)\.py$")
_PUBLIC_TEST_RE = re.compile(r"^test_([A-Za-z0-9][A-Za-z0-9_]*)\.py$")

# Allowed at tests/ root. STRICT: only pytest infrastructure files —
# no test files. Module-mirror tests belong under tests/<pkg>/; cross-
# cutting tests belong in their category subdir (tests/integration/,
# tests/e2e/, tests/examples/, …). If a legitimate exception comes up,
# update this set rather than letting tests-at-root drift back in.
_META_TESTS_AT_ROOT = frozenset(
    {
        "__init__.py",
        "conftest.py",
    }
)

# Categories whose §2 (src ↔ tests mirror) checks are skipped.
# Templates are scaffolds; datasets are data-only; archived entries are
# read-only history. The §1, §3, §4 rules still apply.
_MIRROR_EXEMPT_CATEGORIES = frozenset({"template", "dataset"})

# Recognized test-category subdirectories at tests/ root.
# A repo's tests/ subdirs must come from this set (or be the package mirror
# tests/<pkg>/). Anything else is flagged as PS-207.
# See _skills/general/02_package/01_project-structure-root.md §"./tests".
_KNOWN_TEST_SUBDIRS = frozenset(
    {
        "scripts",  # mirror of ./scripts/ (research projects)
        "examples",  # one test per ./examples/ file
        "skills",  # structural tests for _skills/
        "agentic",  # agentic-trigger tests (LLM invokes the skill)
        "integration",  # cross-module / cross-package
        "smoke",  # fast (<60s) CLI happy-path subprocess tests (PS-211)
        "e2e",  # end-to-end pipelines (PS-212)
        "github_actions",
        "coverage",  # HTML / XML reports — gitignored
        "results",  # general test-run artifacts spanning topics
        # (coverage data files, fixtures output, captured payloads) — gitignored
        "logs",  # pytest run logs — gitignored
        "reports",  # agent-generated summaries — optional
        "custom",  # legacy: tests with no source counterpart
        "develop",  # dev-hygiene tests (audit conformance, etc.) —
        # generated by `scitex-dev ecosystem write-audit-test`
        "__pycache__",  # always present, never our concern
    }
)

# Path-substring blacklist for walks (mirrors the prior-art shell script's
# EXCLUDE_PATHS in scitex-python/tests/sync_tests_with_source.sh).
_WALK_BLACKLIST_RE = re.compile(
    r"(?:^|/)("
    r"\..*"  # hidden dirs (.old, .git, .pytest_cache, ...)
    r"|deprecated.*"
    r"|archive.*"
    r"|backup.*"
    r"|tmp.*"
    r"|temp.*"
    r"|RUNNING"
    r"|FINISHED"
    r"|FINISHED_SUCCESS"
    r"|2024Y.*"
    r"|2025Y.*"
    r"|2026Y.*"
    r"|__pycache__"
    r")(?:/|$)"
)


def _is_blacklisted(path: Path, root: Path) -> bool:
    """True if any path component below `root` is in the blacklist."""
    try:
        rel = path.relative_to(root).as_posix()
    except ValueError:
        return False
    return bool(_WALK_BLACKLIST_RE.search(rel))


# Forbidden top-level directories.
_FORBIDDEN_TOP_DIRS = {
    "mgmt": "no longer used in scitex (see _skills/general/02_package/01_project-structure-root.md)",
    "references": "no longer used in scitex",
    "htmlcov": "coverage reports should live in tests/coverage/",
    "assets": "use ./docs/assets/ instead",
    ".playground": "collapsed into .dev/ for easier typing",
    "logs": "runtime artifact — move to ./GITIGNORED/logs/ or ./tests/logs/ and add to .gitignore",
    "catboost_info": "CatBoost training artifact — must be gitignored (add `catboost_info/` to .gitignore)",
    "signatures": "scratch dir — move to ./GITIGNORED/signatures/ if needed locally",
    "scitex": "orphan module dir — the real package lives in src/<pkg>/. Use a hidden ./.scitex/ for runtime state, never a visible ./scitex/.",
    "unknown_out": "@stx.session output landed at repo root — re-run from a script directory or set CONFIG.SDIR_RUN. Move the dir aside if you need to keep it.",
}

# Top-level junk-file patterns (substring match on the basename).
_JUNK_FILE_RE = re.compile(
    r"^(tmp.*\.(py|ipynb)|quick.*\.py|scratch.*\.py|untitled.*\.(py|ipynb)|debug\.log|.*\.tmp)$"
)
