"""The audit gate must be unmissable from a PARTIAL local run.

The trap we shipped
-------------------
`install-audit-gate` writes the gate to ``tests/develop/test_audit.py``
— OUTSIDE ``tests/<pkg>/``, the directory anyone naturally runs while
working on the package. So ``pytest tests/scitex_storage/`` reports a
clean green having never executed the gate, and the first thing that
runs it is CI. Measured 2026-07-29: scitex-storage's CI went red on 4
audit errors after a local green, for exactly this reason — the second
time it had happened to them. Their conclusion is the one this module
implements: **"I have a written note to myself saying 'run the whole
tests/ tree'. A note is not a gate."**

The defect is OURS: we generate the gate and place it where the obvious
local command misses it, which makes it opt-in by accident.

Why not just move it
--------------------
``tests/develop/`` is load-bearing, not arbitrary. It is the declared
canonical home for generated gate tests
(``_skills/general/02_package/06_project-structure-tests.md`` §tests
layout, which explicitly replaced the deprecated ``tests/skills/``), and
it is addressed BY PATH from at least five places:
``ecosystem test-remote --audit-only`` (``tests/develop/`` is its whole
tier selector), the dashboard's skip-rule extractor
(``_dashboard/_state.py``), the pre-push hook, the audit-project PS-150
pin rule's diagnostics, and the quality workflow's own comment. Moving
it would silently break the ``--audit-only`` tier and the dashboard for
every repo that has ever adopted the gate.

So the location stays and the MISS is made impossible instead.

What the guard does
-------------------
A ``tests/conftest.py`` hook pair. ``tests/conftest.py`` is loaded for
any run under ``tests/`` — including ``pytest tests/<pkg>/`` — because
pytest loads conftests from the rootdir down to the collected paths.

* collection: record whether the gate file was collected at all.
* per-test report: record whether the gate actually RAN.
* session finish: if the session is about to report SUCCESS and neither
  signal ever fired, fail it and say why.

Why TWO signals, not just collection
------------------------------------
Under ``pytest-xdist`` (``pytest tests/ -n auto`` — what this repo's own
CI runs) collection happens in the WORKERS, so the controller process
never calls ``pytest_collection_modifyitems`` and its flag stays False.
The controller is also the only process whose ``pytest_sessionfinish``
decides the session's exit status, so a collection-only guard converts
a fully green ``-n auto`` run — gate collected, gate passed — into a red
one, claiming the gate never ran while its result is right there in the
report stream. Measured on scitex-dev PR #448: 5183 passed, exit 1.

``pytest_runtest_logreport`` is the signal that DOES reach the
controller: xdist forwards every worker's reports to it. Collection is
kept as the second signal because it is the only one that fires for a
session which collects the gate without running it (``--collect-only``,
or a fail-fast exit before the gate's turn).

A session that is ALREADY red is left alone — the developer is
iterating and can see the failures; converting their red into a
differently-worded red helps nobody. The one case that changes is the
dangerous one: an unqualified green from a run that never executed the
gate. A check that could not run must not report what a check that
passed reports.

Escape hatch: ``SCITEX_DEV_ALLOW_PARTIAL_RUN=1``. Explicit, named in the
failure message, and visible in shell history — unlike a note.
"""

from __future__ import annotations

GUARD_BEGIN = "# >>> scitex-dev audit-gate collection guard >>>"
GUARD_END = "# <<< scitex-dev audit-gate collection guard <<<"

#: Where `install-audit-gate` writes the gate, relative to the package
#: root. The guard reads it from here so the two can never disagree.
GATE_RELPARTS = ("tests", "develop", "test_audit.py")

OPT_OUT_ENV_VAR = "SCITEX_DEV_ALLOW_PARTIAL_RUN"


def render_guard_block() -> str:
    """The marked conftest block implementing the guard.

    Emitted verbatim into the consumer's ``tests/conftest.py``. Names are
    ``_stx_``-prefixed so the block cannot collide with fixtures or
    helpers the package already defines in the same file.
    """
    gate_rel = "/".join(GATE_RELPARTS)
    return f'''{GUARD_BEGIN}
# Generated by `scitex-dev ecosystem install-audit-gate`. Regenerate with
# that command; edits inside this block are overwritten.
#
# WHY: the audit gate lives at {gate_rel}, outside the
# tests/<pkg>/ directory you naturally run while working. Without this,
# `pytest tests/<pkg>/` reports a clean green having never run the gate,
# and CI is the first thing that does.
#
# WHAT: a session that would otherwise report SUCCESS, but never
# collected OR ran the gate, fails instead — naming the reason. An
# already-red session is left alone. Opt out for one run with
# {OPT_OUT_ENV_VAR}=1.
import os as _stx_os
from pathlib import Path as _stx_Path

_STX_GATE_RELPARTS = {GATE_RELPARTS!r}
_STX_GATE_NODEID_PREFIX = {gate_rel!r}
_STX_OPT_OUT = {OPT_OUT_ENV_VAR!r}
_stx_gate_seen = False


def _stx_gate_path(config):
    """Absolute path of the audit gate for this rootdir."""
    root = getattr(config, "rootpath", None) or getattr(config, "rootdir", "")
    return _stx_Path(str(root)).joinpath(*_STX_GATE_RELPARTS)


def pytest_collection_modifyitems(session, config, items):
    """Record the gate being COLLECTED (fires in-process / in xdist workers).

    The only signal that fires for a session which collects the gate
    without running it (``--collect-only``, or an early exit).
    """
    global _stx_gate_seen
    try:
        gate = _stx_gate_path(config).resolve()
    except OSError:  # pragma: no cover - defensive
        return
    for item in items:
        try:
            if _stx_Path(str(item.fspath)).resolve() == gate:
                _stx_gate_seen = True
                return
        except OSError:  # pragma: no cover - defensive
            continue


def pytest_runtest_logreport(report):
    """Record the gate RUNNING — the signal that reaches an xdist controller.

    Under ``-n auto`` the controller never collects, so the collection
    hook above never fires there; xdist DOES forward every worker's test
    reports to it. Without this, a fully green ``-n auto`` run that
    collected and passed the gate is still reported as gate-less.
    ``nodeid`` is always rootdir-relative with ``/`` separators.
    """
    global _stx_gate_seen
    if _stx_gate_seen:
        return
    nodeid = getattr(report, "nodeid", "") or ""
    if nodeid.split("::", 1)[0] == _STX_GATE_NODEID_PREFIX:
        _stx_gate_seen = True


def pytest_sessionfinish(session, exitstatus):
    """Turn an unqualified green from a gate-less run into a loud red."""
    if _stx_gate_seen or exitstatus != 0:
        return
    config = session.config
    if hasattr(config, "workerinput"):
        return  # xdist worker; the controller reports for the session
    if _stx_os.environ.get(_STX_OPT_OUT):
        return
    gate = _stx_gate_path(config)
    if not gate.is_file():
        return  # this repo has no audit gate installed - nothing to miss
    message = (
        "AUDIT GATE DID NOT RUN IN THIS SESSION.\\n"
        f"  {{gate}} was never collected, so this green says nothing "
        "about audit conformance -\\n"
        "  it is the same green you would get with the gate failing.\\n"
        "  Run the whole tree:  pytest tests/\\n"
        f"  Or accept a partial run for THIS run:  {{_STX_OPT_OUT}}=1 pytest ..."
    )
    reporter = config.pluginmanager.get_plugin("terminalreporter")
    if reporter is not None:
        reporter.write_sep("=", "audit gate not collected", red=True, bold=True)
        for line in message.splitlines():
            reporter.write_line(line, red=True)
    else:  # pragma: no cover - terminal plugin disabled
        print(message)
    session.exitstatus = 1
{GUARD_END}
'''


def render_conftest(existing: str | None) -> tuple[str, str]:
    """Return ``(content, action)`` for the consumer's ``tests/conftest.py``.

    ``action`` is ``"created"`` / ``"updated"`` / ``"current"``. An
    EXISTING conftest is appended to rather than replaced: nearly every
    adopted repo already has one, and skipping those (the previous
    behaviour for this file) would leave the guard reaching only brand
    new repos — the same accidental opt-in the guard exists to remove.
    The block is delimited by markers, so re-running is idempotent and a
    refresh replaces exactly the block and nothing else.
    """
    block = render_guard_block()
    if existing is None:
        return _HEADER + "\n" + block, "created"
    if GUARD_BEGIN in existing:
        if GUARD_END not in existing:
            # Truncated/hand-mangled block: append a fresh one rather
            # than guess where the old one was meant to end.
            return existing.rstrip("\n") + "\n\n" + block, "updated"
        head, _, rest = existing.partition(GUARD_BEGIN)
        _, _, tail = rest.partition(GUARD_END)
        rebuilt = head.rstrip("\n") + "\n\n" + block + tail.lstrip("\n")
        return rebuilt, ("current" if rebuilt == existing else "updated")
    return existing.rstrip("\n") + "\n\n" + block, "updated"


_HEADER = '''"""Pytest fixtures and rootdir marker for this package.

A conftest.py at tests/ is the canonical SciTeX convention: it pins the
pytest rootdir, gives downstream fixtures a home, and carries the
audit-gate collection guard below.
"""
'''


__all__ = [
    "GATE_RELPARTS",
    "GUARD_BEGIN",
    "GUARD_END",
    "OPT_OUT_ENV_VAR",
    "render_conftest",
    "render_guard_block",
]
