#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ecosystem `install-audit-gate` (+ deprecated `write-audit-test` alias)."""

import click


def register(ecosystem):
    @ecosystem.command(
        "install-audit-gate",
        epilog=(
            "Examples:\n"
            "  $ scitex-dev ecosystem install-audit-gate scitex-types\n"
            "  $ scitex-dev ecosystem install-audit-gate scitex-io --force\n"
            "  $ scitex-dev ecosystem install-audit-gate scitex-io --dry-run\n"
            "\n"
            "Wires the audit-conformance gate into the package's own\n"
            "test suite by materialising `tests/develop/test_audit.py`.\n"
            "The generated test calls\n"
            "`scitex_dev.testing.audit_all_for_package(<pkg>)` and\n"
            "fails when any error-severity violation is reported, so\n"
            "the existing `Test` workflow surfaces audit drift — no\n"
            "separate `.github/workflows/audit.yml` needed. Also\n"
            "creates `tests/develop/__init__.py` and an empty\n"
            "`tests/conftest.py` if either is missing.\n"
            "\n"
            "This does NOT generate stub tests for the package's source\n"
            "modules — it ONLY installs the canonical audit gate.\n"
            "Quality of source-coverage tests is the package author's\n"
            "responsibility (see PS-206 / PS-206b for the rules that\n"
            "enforce non-trivial test bodies).\n"
        ),
    )
    @click.argument("distribution")
    @click.option("--force", is_flag=True, help="Overwrite an existing test_audit.py.")
    @click.option(
        "--dry-run",
        is_flag=True,
        help="Print the target paths and contents without writing.",
    )
    @click.option("--yes", "-y", is_flag=True, help="Skip confirmation prompt.")
    def ecosystem_install_audit_gate(distribution, force, dry_run, yes):
        """Install the audit-conformance gate test for DISTRIBUTION.

        Wires `scitex-dev ecosystem audit-all <pkg>` into the package's
        test suite as `tests/develop/test_audit.py`. Does NOT generate
        stub tests for source modules.
        """
        del yes  # generation is non-destructive when --force is absent
        from ...._ecosystem import ECOSYSTEM, get_local_path

        if distribution not in ECOSYSTEM:
            click.echo(f"error: '{distribution}' not in ECOSYSTEM", err=True)
            raise SystemExit(2)
        info = ECOSYSTEM[distribution]
        if info.get("archived"):
            click.echo(f"skip  {distribution}: archived", err=True)
            raise SystemExit(0)

        local = get_local_path(distribution)
        if local is None or not local.exists():
            click.echo(
                f"error: local path for '{distribution}' missing: {local}",
                err=True,
            )
            raise SystemExit(2)

        tests = local / "tests"
        develop = tests / "develop"
        target = develop / "test_audit.py"
        develop_init = develop / "__init__.py"
        conftest = tests / "conftest.py"

        test_content = (
            '"""Audit conformance — runs `scitex-dev ecosystem audit-all`\n'
            "on this package as a normal test. Generated by\n"
            "`scitex-dev ecosystem install-audit-gate`. Re-run that command\n"
            "after upgrading scitex-dev to refresh any pin in [dev].\n"
            "\n"
            "Bypass (exceptions / temporal remedy):\n"
            "    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .\n"
            "\n"
            "Use when remediating pre-existing violations or developing\n"
            "without the audit corpus available locally. CI for release\n"
            "branches MUST NOT set this — drift goes silent.\n"
            '"""\n'
            "\n"
            "import shutil\n"
            "\n"
            "import pytest\n"
            "\n"
            "\n"
            "@pytest.mark.skipif(\n"
            '    shutil.which("scitex-dev") is None,\n'
            '    reason="scitex-dev not installed — add `scitex-dev[cli-audit]` '
            'to [project.optional-dependencies.dev]",\n'
            ")\n"
            "def test_audit_all_clean():\n"
            "    # Arrange\n"
            "    from scitex_dev.testing import audit_all_for_package\n"
            "\n"
            "    # Act\n"
            f"    result = audit_all_for_package({distribution!r})\n"
            "\n"
            "    # Assert — audit_all_for_package returns None on a clean\n"
            "    # audit and raises AssertionError on any unexpected finding,\n"
            "    # so reaching this point with result is None means clean.\n"
            "    assert result is None\n"
        )
        develop_init_content = (
            '"""Dev-hygiene tests — audit conformance, etc.\n'
            "\n"
            "Tests in this directory exercise the package's compliance\n"
            "with ecosystem-wide rules (CLI/MCP/skills/project structure)\n"
            "via `scitex-dev ecosystem audit-all`. They are not unit tests\n"
            "of the package's own logic; those live under tests/<pkg>/.\n"
            '"""\n'
        )
        conftest_content = (
            '"""Pytest fixtures and rootdir marker for this package.\n'
            "\n"
            "An empty conftest.py at tests/ is the canonical SciTeX\n"
            "convention (audit-project PS-208) — it pins the pytest\n"
            "rootdir and gives downstream fixtures a home.\n"
            '"""\n'
        )

        # Each entry: (path, content, force_required_to_overwrite).
        # tests/develop/__init__.py and tests/conftest.py are *only*
        # written when missing — they're shared infrastructure, never
        # owned by the audit-test feature. The test_audit.py file IS
        # owned: --force overwrites it on every regeneration.
        plan = [
            (target, test_content, True),
            (develop_init, develop_init_content, False),
            (conftest, conftest_content, False),
        ]

        if dry_run:
            for path, content, _ in plan:
                click.echo(f"# would write: {path}")
                click.echo(content)
                click.echo()
            return

        for path, content, owned in plan:
            if path.exists():
                if owned and not force:
                    click.echo(
                        f"error: {path} already exists (pass --force to overwrite)",
                        err=True,
                    )
                    raise SystemExit(1)
                if not owned:
                    # Don't touch user-owned conftest/__init__ if present.
                    continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            click.echo(f"wrote {path}")

    # Deprecated alias — write-audit-test was misleading (read like
    # "auto-generate stub tests"); the actual behaviour is "install the
    # audit-conformance gate". Kept hidden for one minor release so
    # external scripts/CI that call the old name don't break.
    @ecosystem.command("write-audit-test", hidden=True)
    @click.argument("distribution")
    @click.option("--force", is_flag=True)
    @click.option("--dry-run", is_flag=True)
    @click.option("--yes", "-y", is_flag=True)
    @click.pass_context
    def ecosystem_write_audit_test_deprecated(ctx, distribution, force, dry_run, yes):
        """(deprecated) Use `install-audit-gate`."""
        click.secho(
            "warning: `scitex-dev ecosystem write-audit-test` is deprecated; "
            "use `scitex-dev ecosystem install-audit-gate` (same behaviour, "
            "honest name).",
            fg="yellow",
            err=True,
        )
        ctx.invoke(
            ecosystem_install_audit_gate,
            distribution=distribution,
            force=force,
            dry_run=dry_run,
            yes=yes,
        )
