#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ecosystem `install-audit-gate` (+ deprecated `write-audit-test` alias)."""

from pathlib import Path

import click

from ...._ecosystem.help_spec import CliHelp, Example, SpecCommand
from ._gate_guard import render_conftest


def anchor_depth(target: Path, root: Path) -> int:
    """`parents[N]` index that walks from ``target`` back up to ``root``.

    ``Path(__file__).resolve().parents[N]`` counts DIRECTORY levels, so
    N is the number of path components between the file and the root:
    ``tests/develop/test_audit.py`` → 2, ``tests/test_audit.py`` → 1.

    Derived, never hardcoded. The generator writes the gate at
    ``tests/develop/test_audit.py`` while `audit_all_for_package`'s
    docstring example is written for ``tests/test_audit.py`` — a
    hardcoded ``parents[1]`` copied from that example resolves to
    ``tests/`` and the audit then grades a SUBDIRECTORY as if it were
    the package (measured by scitex-storage against v0.38.1). Computing
    N from the emitted file's own location is the only shape that stays
    correct if the gate is ever written at a different depth.
    """
    rel = Path(target).resolve().relative_to(Path(root).resolve())
    return len(rel.parts) - 1


def render_audit_gate(distribution: str, target: Path, root: Path) -> str:
    """Source of the generated ``test_audit.py`` for ``distribution``.

    ``target`` is where the file will be written and ``root`` the
    package root it must resolve back to; the ``path=`` anchor is
    computed from the pair (see :func:`anchor_depth`).
    """
    n = anchor_depth(target, root)
    return (
        '"""Audit conformance — runs `scitex-dev ecosystem audit-all`\n'
        "on this package as a normal test. Generated by\n"
        "`scitex-dev ecosystem install-audit-gate`. Re-run that command\n"
        "after upgrading scitex-dev to refresh any pin in [dev].\n"
        "\n"
        "Bypass (exceptions / temporal remedy):\n"
        "    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .\n"
        "\n"
        "Use when remediating pre-existing violations or developing\n"
        "without the audit corpus available locally. CI for release\n"
        "branches MUST NOT set this — drift goes silent.\n"
        '"""\n'
        "\n"
        "import shutil\n"
        "from pathlib import Path\n"
        "\n"
        "import pytest\n"
        "\n"
        "\n"
        "@pytest.mark.skipif(\n"
        '    shutil.which("scitex-dev") is None,\n'
        '    reason="scitex-dev not installed — add `scitex-dev[cli-audit]` '
        'to [project.optional-dependencies.dev]",\n'
        ")\n"
        "# audit-all fans out to 6 sub-auditor subprocesses (audit-cli,\n"
        "# audit-mcp-tools, audit-skills, audit-python-apis, audit-project,\n"
        "# audit-django), each re-importing the package fresh; on a loaded\n"
        "# or NFS-backed host this legitimately runs well past this repo's\n"
        "# global [tool.pytest.ini_options] `timeout` default even when the\n"
        "# audit itself is completely clean. Override per-test rather than\n"
        "# raise the global cap for every other (fast) test.\n"
        "@pytest.mark.timeout(600)\n"
        "def test_audit_all_clean():\n"
        "    # Arrange\n"
        "    from scitex_dev.testing import audit_all_for_package\n"
        "\n"
        "    # `path=` PINS the tree under audit to THIS checkout. Without\n"
        "    # it the auditor falls back to guessing from the cwd, which\n"
        "    # grades the parent repo when pytest runs from a git worktree\n"
        "    # and somebody else's tree on a shared runner. A gate that\n"
        "    # grades the wrong tree is worse than no gate.\n"
        f"    # This file lives at {'/'.join(Path(target).resolve().relative_to(Path(root).resolve()).parts)},\n"
        f"    # so parents[{n}] is the package root.\n"
        "\n"
        "    # Act\n"
        "    result = audit_all_for_package(\n"
        f"        {distribution!r},\n"
        f"        path=Path(__file__).resolve().parents[{n}],\n"
        "    )\n"
        "\n"
        "    # Assert — audit_all_for_package returns None on a clean\n"
        "    # audit and raises AssertionError on any unexpected finding,\n"
        "    # so reaching this point with result is None means clean.\n"
        "    assert result is None\n"
    )


def register(ecosystem):
    @ecosystem.command(
        "install-audit-gate",
        cls=SpecCommand,
        help_spec=CliHelp(
            summary="Install the audit-conformance gate test for DISTRIBUTION.",
            description=(
                "Wires `ecosystem audit-all <pkg>` into the package's "
                "own test suite by materialising "
                "`tests/develop/test_audit.py`, which calls "
                "`scitex_dev.testing.audit_all_for_package(<pkg>)` and "
                "fails when any error-severity violation is reported — "
                "so the existing `Test` workflow surfaces audit drift, "
                "no separate `.github/workflows/audit.yml` needed. Also "
                "creates `tests/develop/__init__.py` if missing, and "
                "installs the audit-gate COLLECTION GUARD into "
                "`tests/conftest.py` (a marked, idempotent block appended "
                "to whatever is already there): because the gate lives "
                "outside `tests/<pkg>/`, `pytest tests/<pkg>/` used to "
                "report a clean green having never run it. The guard "
                "fails any session that would otherwise report success "
                "without collecting the gate — opt out per-run with "
                "`SCITEX_DEV_ALLOW_PARTIAL_RUN=1`. This does "
                "NOT generate stub tests for the package's source "
                "modules — it ONLY installs the canonical audit gate; "
                "source-coverage test quality remains the package "
                "author's responsibility (PS-206 / PS-206b).",
            ),
            examples=(
                Example(
                    "{prog} ecosystem install-audit-gate scitex-types",
                    "Install the gate.",
                ),
                Example(
                    "{prog} ecosystem install-audit-gate scitex-io --force",
                    "Overwrite an existing gate.",
                ),
                Example(
                    "{prog} ecosystem install-audit-gate scitex-io --dry-run",
                    "Preview without writing.",
                ),
            ),
        ),
    )
    @click.argument("distribution")
    @click.option("--force", is_flag=True, help="Overwrite an existing test_audit.py.")
    @click.option(
        "--dry-run",
        is_flag=True,
        help="Print the target paths and contents without writing.",
    )
    @click.option(
        "--path",
        default=None,
        help=(
            "Checkout to write into. Same semantics as `audit-all --path`. "
            "Without it the cwd's repository is used; the `~/proj/<name>` "
            "registry guess is the last resort and is announced when used."
        ),
    )
    @click.option("--yes", "-y", is_flag=True, help="Skip confirmation prompt.")
    def ecosystem_install_audit_gate(distribution, force, dry_run, path, yes):
        del yes  # generation is non-destructive when --force is absent
        from ...._ecosystem import ECOSYSTEM
        from ._write_target import (
            assert_target_is_distribution,
            resolve_write_target,
        )

        if distribution not in ECOSYSTEM:
            click.echo(f"error: '{distribution}' not in ECOSYSTEM", err=True)
            raise SystemExit(2)
        info = ECOSYSTEM[distribution]
        if info.get("archived"):
            click.echo(f"skip  {distribution}: archived", err=True)
            raise SystemExit(0)

        # This verb writes THREE files, one of which APPENDS to an existing
        # `tests/conftest.py`. It previously resolved its target with the
        # ECOSYSTEM `~/proj/<name>` guess and had no --path — the same shape
        # that made `install-cross-package-gate` write into a checkout
        # nobody named (measured 2026-07-29). Guard before touching anything.
        local, target_source = resolve_write_target(distribution, path)
        if local is None or not local.exists():
            click.echo(
                f"error: local path for '{distribution}' missing: {local}",
                err=True,
            )
            raise SystemExit(2)

        assert_target_is_distribution(local, distribution, target_source)

        tests = local / "tests"
        develop = tests / "develop"
        target = develop / "test_audit.py"
        develop_init = develop / "__init__.py"
        conftest = tests / "conftest.py"

        test_content = render_audit_gate(distribution, target, local)
        develop_init_content = (
            '"""Dev-hygiene tests — audit conformance, etc.\n'
            "\n"
            "Tests in this directory exercise the package's compliance\n"
            "with ecosystem-wide rules (CLI/MCP/skills/project structure)\n"
            "via `scitex-dev ecosystem audit-all`. They are not unit tests\n"
            "of the package's own logic; those live under tests/<pkg>/.\n"
            '"""\n'
        )
        # tests/conftest.py carries the collection guard, so it can no
        # longer be skipped when it already exists — nearly every adopted
        # repo has one, and skipping those would leave the guard reaching
        # only brand new repos. `render_conftest` APPENDS a marked block
        # to an existing file (idempotent, refreshes in place) instead of
        # replacing the package's own fixtures.
        existing_conftest = conftest.read_text() if conftest.exists() else None
        conftest_content, conftest_action = render_conftest(existing_conftest)

        # Each entry: (path, content, force_required_to_overwrite).
        # tests/develop/__init__.py is *only* written when missing — it's
        # shared infrastructure, never owned by the audit-test feature.
        # test_audit.py IS owned: --force overwrites it on every
        # regeneration.
        plan = [
            (target, test_content, True),
            (develop_init, develop_init_content, False),
        ]

        if dry_run:
            for path, content, _ in plan:
                click.echo(f"# would write: {path}")
                click.echo(content)
                click.echo()
            click.echo(f"# would {conftest_action}: {conftest}")
            click.echo(conftest_content)
            click.echo()
            return

        for path, content, owned in plan:
            if path.exists():
                if owned and not force:
                    click.echo(
                        f"error: {path} already exists (pass --force to overwrite)",
                        err=True,
                    )
                    raise SystemExit(1)
                if not owned:
                    # Don't touch a user-owned __init__ if present.
                    continue
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            click.echo(f"wrote {path}")

        if conftest_action != "current":
            conftest.parent.mkdir(parents=True, exist_ok=True)
            conftest.write_text(conftest_content)
            click.echo(
                f"{'wrote' if conftest_action == 'created' else 'updated'} "
                f"{conftest} (audit-gate collection guard)"
            )

    # Deprecated alias — write-audit-test was misleading (read like
    # "auto-generate stub tests"); the actual behaviour is "install the
    # audit-conformance gate". Kept hidden for one minor release so
    # external scripts/CI that call the old name don't break.
    @ecosystem.command("write-audit-test", hidden=True)
    @click.argument("distribution")
    @click.option("--force", is_flag=True)
    @click.option("--dry-run", is_flag=True)
    @click.option("--yes", "-y", is_flag=True)
    @click.pass_context
    def ecosystem_write_audit_test_deprecated(ctx, distribution, force, dry_run, yes):
        """(deprecated) Use `install-audit-gate`."""
        click.secho(
            "warning: `scitex-dev ecosystem write-audit-test` is deprecated; "
            "use `scitex-dev ecosystem install-audit-gate` (same behaviour, "
            "honest name).",
            fg="yellow",
            err=True,
        )
        ctx.invoke(
            ecosystem_install_audit_gate,
            distribution=distribution,
            force=force,
            dry_run=dry_run,
            yes=yes,
        )
