#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ecosystem `install-cross-package-gate` — materialise the PS-140 gate.

PS-140 requires any package with cross-package imports to ship
`tests/integration/test_cross_package_imports.py` declaring every
cross-package module name. The rule has DETECTED that gap since it was
written, but its remediation text pointed at
`python /tmp/write-integration-tests.py <pkg-dir>` — a path in a
world-writable directory, shipped nowhere, hedged in the rule text
itself with "(or the equivalent scitex-dev subcommand)". No such
subcommand existed. Reported by scitex-hpc, 2026-07-29, who hit the
remediation, found nothing to run, and hand-edited a block whose own
header says it is auto-generated.

A check that can detect but not remediate pushes a careful reader into
doing by hand the thing the file warns against. That is the check's
defect, not the reader's.

SSoT: the expected-import set is computed by importing
:func:`_collect_cross_package_imports` FROM the PS-140 checker — the
same function the audit grades against. The previous arrangement had
the checker's docstring promise to "mirror" the /tmp script; two
implementations of one fact drift silently, and this one drifted all
the way to nonexistence. Generator and gate now cannot disagree,
because there is only one of them.
"""

import subprocess
from pathlib import Path

import click

from ...._ecosystem.help_spec import CliHelp, Example, SpecCommand
from ...audit._project._check_umbrella_dep_and_integration import (
    _collect_cross_package_imports,
    _own_import_name,
)
from ._write_target import assert_target_is_distribution, resolve_write_target


def render_cross_package_gate(distribution: str, imports: list[str]) -> str:
    """Source of the generated `test_cross_package_imports.py`.

    `imports` is rendered as the `CROSS_PACKAGE_IMPORTS` list literal
    that PS-140's `_read_declared_imports` parses back out via AST, so
    the emitted shape is the one the auditor can actually read (a plain
    `Assign` of a `List` of string `Constant`s — not an f-string, a
    comprehension, or a tuple).
    """
    listed = "\n".join(f"    {name!r}," for name in sorted(imports))
    return (
        '"""Cross-package import gate (PS-140) for ' + distribution + ".\n"
        "\n"
        "Every module listed here is imported by this package's source but\n"
        "OWNED by a peer standalone. A rename or move on the other side of\n"
        "that boundary is invisible to this package's unit tests and\n"
        "surfaces as ModuleNotFoundError in a user's process — which is how\n"
        "the `scitex_io._load_cache` rename went undetected for weeks.\n"
        "\n"
        "Generated by `scitex-dev ecosystem install-cross-package-gate`.\n"
        "Regenerate with:\n"
        "\n"
        "    scitex-dev ecosystem install-cross-package-gate "
        + distribution
        + " --force\n"
        "\n"
        "Do not hand-edit the list: the PS-140 auditor recomputes it from\n"
        "source on every run and fails on any drift in either direction\n"
        "(a missing entry OR a stale one).\n"
        '"""\n'
        "\n"
        "import importlib\n"
        "\n"
        "import pytest\n"
        "\n"
        "CROSS_PACKAGE_IMPORTS = [\n" + listed + "\n"
        "]\n"
        "\n"
        "\n"
        '@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)\n'
        "def test_cross_package_import_resolves(module_name):\n"
        "    # Arrange / Act — a real import, not importlib.util.find_spec:\n"
        "    # find_spec only proves a module is FINDABLE on the path, and\n"
        "    # the failures this gate exists to catch (a renamed symbol\n"
        "    # re-exported through a package __init__) happen at EXECUTION.\n"
        "    module = importlib.import_module(module_name)\n"
        "\n"
        "    # Assert\n"
        "    assert module is not None\n"
    )


def register(ecosystem):
    @ecosystem.command(
        "install-cross-package-gate",
        cls=SpecCommand,
        help_spec=CliHelp(
            summary=(
                "Install the PS-140 cross-package import gate for DISTRIBUTION."
            ),
            description=(
                "Materialises "
                "`tests/integration/test_cross_package_imports.py` "
                "declaring every module this package imports from a peer "
                "standalone (`scitex_<X>`) or the umbrella (`scitex.<X>`), "
                "each asserted with a real `import_module` call. The list "
                "is computed by the SAME function the PS-140 auditor "
                "grades against, so a freshly generated gate is clean by "
                "construction. Also creates `tests/integration/__init__.py` "
                "if missing. Re-run with `--force` after adding or "
                "removing a cross-package import — PS-140 fails on drift "
                "in either direction, so a stale entry is a violation too."
            ),
            examples=(
                Example(
                    "{prog} ecosystem install-cross-package-gate scitex-hpc",
                    "Install the gate.",
                ),
                Example(
                    "{prog} ecosystem install-cross-package-gate scitex-hpc --force",
                    "Regenerate after the import set changed.",
                ),
                Example(
                    "{prog} ecosystem install-cross-package-gate scitex-hpc --dry-run",
                    "Preview without writing.",
                ),
            ),
        ),
    )
    @click.argument("distribution")
    @click.option(
        "--force", is_flag=True, help="Overwrite an existing gate file."
    )
    @click.option(
        "--dry-run",
        is_flag=True,
        help="Print the target path and contents without writing.",
    )
    @click.option(
        "--path",
        default=None,
        help=(
            "Checkout to write into. Same semantics as `audit-all --path`. "
            "Without it the cwd's repository is used; the "
            "`~/proj/<name>` registry guess is the last resort and is "
            "announced when used."
        ),
    )
    @click.option("--yes", "-y", is_flag=True, help="Skip confirmation prompt.")
    def ecosystem_install_cross_package_gate(distribution, force, dry_run, path, yes):
        # `install` is a MUTATING verb, so §2 of the CLI conventions requires a
        # --yes/-y flag on it regardless of how safe this particular
        # implementation is. Generation here is non-destructive without
        # --force, so nothing is gated on it today — but the flag is part of
        # the published shape of a mutating verb, and `install-audit-gate`
        # carries it for the same reason.
        del yes
        from ...._ecosystem import ECOSYSTEM, get_local_path

        if distribution not in ECOSYSTEM:
            click.echo(f"error: '{distribution}' not in ECOSYSTEM", err=True)
            raise SystemExit(2)
        info = ECOSYSTEM[distribution]
        if info.get("archived"):
            click.echo(f"skip  {distribution}: archived", err=True)
            raise SystemExit(0)

        local, target_source = resolve_write_target(distribution, path)
        if local is None or not local.exists():
            click.echo(
                f"error: local path for '{distribution}' missing: {local}",
                err=True,
            )
            raise SystemExit(2)

        assert_target_is_distribution(local, distribution, target_source)

        src_root = local / "src"
        if not src_root.exists():
            click.echo(
                f"error: {distribution} has no src/ at {src_root} — "
                "PS-140 only applies to src-layout packages",
                err=True,
            )
            raise SystemExit(2)

        own = _own_import_name(local)
        imports = sorted(_collect_cross_package_imports(src_root, own))
        target = local / "tests" / "integration" / "test_cross_package_imports.py"

        # No cross-package imports means PS-140 does not require the gate
        # at all. Writing an empty one would parametrize over nothing and
        # report green over zero assertions — a gate that cannot fail.
        if not imports:
            click.echo(
                f"{distribution}: no cross-package imports found under "
                f"{src_root} — PS-140 does not require a gate here, "
                "nothing written."
            )
            if target.exists():
                click.echo(
                    f"note: {target} exists but the import set is now empty; "
                    "PS-140 flags stale entries, so delete it or remove the "
                    "stale names by hand.",
                    err=True,
                )
            return

        content = render_cross_package_gate(distribution, imports)
        init = target.parent / "__init__.py"

        # Show WHAT was computed, not just where it will go. The reported
        # run wrote 3 imports where the branch had 4 — wrong tree in, wrong
        # content out. A gate that under-declares its imports PASSES while
        # missing one, which is exactly the failure PS-140 exists to catch,
        # so a silently-wrong list is worse than no gate.
        click.echo(
            f"computed {len(imports)} cross-package import(s) from {src_root}:",
            err=True,
        )
        for name in imports:
            click.echo(f"  - {name}", err=True)

        if dry_run:
            click.echo(f"# would write: {target}")
            click.echo(content)
            if not init.exists():
                click.echo(f"# would write: {init}")
            return

        if target.exists() and not force:
            click.echo(
                f"error: {target} already exists (pass --force to overwrite)",
                err=True,
            )
            raise SystemExit(1)

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        click.echo(f"wrote {target} ({len(imports)} cross-package import(s))")

        if not init.exists():
            init.write_text(
                '"""Integration tests — cross-package runtime gates."""\n'
            )
            click.echo(f"wrote {init}")

# EOF
