#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Respawn-loop supervisor for hosts WITHOUT systemd ``--user``.

Not every host that runs a SciTeX daemon has a systemd user manager
(headless HPC nodes, minimal containers, macOS without launchd wiring).
On those hosts ``scitex-dev service ensure <name>`` falls back to a
plain shell keep-alive loop that supervises the daemon the same way the
Spartan CI runner (``ci/runner/launcher.sh``) supervises ``./run.sh``:

    while alive-flag-exists; do
        <ExecStart>
        sleep <backoff>   # capped exponential backoff on crash
    done

The loop is written to a script under the package's runtime dir and
launched detached (``setsid nohup``). Idempotency + stoppability come
from two files under ``~/.scitex/<pkg>/runtime/``:

* an **alive flag** — the loop runs only while it exists; ``rm``-ing it
  stops the loop after the current backoff.
* a **pidfile** — holds the supervisor PID so ``ensure`` can detect an
  already-running supervisor and refuse to start a second one.

Per operator directive, ALL state/log output goes under
``~/.scitex/<pkg>/runtime/`` (``.../runtime/logs/<name>.log``), never
``~/.scitex/dev/logs/``.

Everything here is a PURE builder (paths + script text from a JobSpec)
so it is trivially unit-testable; the filesystem writes + the detached
launch live in :mod:`scitex_dev.jobs._ensure`.
"""

from __future__ import annotations

import shlex
from pathlib import Path

from . import JobSpec
from ._systemd import resolve_execstart

#: Backoff schedule for the respawn loop. Mirrors ``launcher.sh``:
#: start at 5s, double on each crash, cap at 5 min so a broken daemon
#: never melts CPU nor hammers a downstream it depends on.
DEFAULT_BACKOFF_START_SEC = 5
DEFAULT_BACKOFF_MAX_SEC = 300


def package_of(job: JobSpec) -> str:
    """Return the owning package slug for ``job``.

    ``JobSpec.name`` is package-prefixed (``"sac.listen"``,
    ``"scitex-todo.dashboard"``). The runtime dir keys off the part
    before the first ``.`` so every daemon a package owns shares one
    ``~/.scitex/<pkg>/runtime/`` tree. A bare name with no ``.`` (the
    legacy scitex-dev built-ins) keys under itself.
    """
    return job.name.split(".", 1)[0]


def runtime_dir(job: JobSpec, *, home: Path | None = None) -> Path:
    """Return ``<home>/.scitex/<pkg>/runtime`` for ``job``.

    ``home`` is a test seam; production passes ``Path.home()``.
    """
    base = home if home is not None else Path.home()
    return base / ".scitex" / package_of(job) / "runtime"


def log_path(job: JobSpec, *, home: Path | None = None) -> Path:
    """Return the supervisor log path under ``runtime/logs/``."""
    return runtime_dir(job, home=home) / "logs" / f"{job.name}.log"


def flag_path(job: JobSpec, *, home: Path | None = None) -> Path:
    """Return the alive-flag path. Loop runs only while this exists."""
    return runtime_dir(job, home=home) / f"{job.name}.alive"


def pidfile_path(job: JobSpec, *, home: Path | None = None) -> Path:
    """Return the supervisor pidfile path."""
    return runtime_dir(job, home=home) / f"{job.name}.pid"


def script_path(job: JobSpec, *, home: Path | None = None) -> Path:
    """Return the path the generated supervisor script is written to."""
    return runtime_dir(job, home=home) / f"{job.name}.respawn.sh"


def build_respawn_script(
    job: JobSpec,
    *,
    home: Path | None = None,
    backoff_start: int = DEFAULT_BACKOFF_START_SEC,
    backoff_max: int = DEFAULT_BACKOFF_MAX_SEC,
) -> str:
    """Return the keep-alive supervisor shell script text for ``job``.

    Pure: JobSpec + paths in, script string out. Models
    ``ci/runner/launcher.sh``'s persistent run loop:

    * loops while the alive-flag exists (``rm`` the flag to stop);
    * writes its own PID into the pidfile;
    * runs the resolved ``ExecStart``, appending stdout+stderr to the
      runtime log;
    * on a clean exit resets the backoff; on a crash sleeps with capped
      exponential backoff before respawning;
    * cleans up the pidfile on TERM/INT.

    ``ExecStart`` is absolutised via :func:`resolve_execstart` for the
    same reason the systemd path does it — a detached loop inherits a
    minimal env and a bare console-script name would 127.
    """
    execstart = resolve_execstart(job.command)
    flag = flag_path(job, home=home)
    pidf = pidfile_path(job, home=home)
    logf = log_path(job, home=home)

    q_flag = shlex.quote(str(flag))
    q_pidf = shlex.quote(str(pidf))
    q_logf = shlex.quote(str(logf))

    return "\n".join(
        [
            "#!/bin/bash",
            f"# Respawn supervisor for {job.name} — generated by",
            "# scitex-dev service ensure (respawn fallback; no systemd --user).",
            "# Stop it by removing the alive flag:",
            f"#   rm {flag}",
            "set -u",
            f"FLAG={q_flag}",
            f"PIDFILE={q_pidf}",
            f"LOGF={q_logf}",
            f'log() {{ printf "[%s] %s\\n" "$(date -Iseconds)" "$*" >>"$LOGF"; }}',
            "",
            "cleanup() {",
            '    log "trap: stopping respawn supervisor"',
            '    rm -f "$PIDFILE"',
            "    exit 0",
            "}",
            "trap cleanup INT TERM",
            "",
            'mkdir -p "$(dirname "$LOGF")"',
            'echo "$$" >"$PIDFILE"',
            f"backoff={backoff_start}",
            f"max_backoff={backoff_max}",
            'while [ -e "$FLAG" ]; do',
            f'    log "starting: {job.command}"',
            f"    if {execstart} >>\"$LOGF\" 2>&1; then",
            '        log "exited cleanly"',
            f"        backoff={backoff_start}",
            "    else",
            "        rc=$?",
            '        log "crashed rc=$rc; backoff ${backoff}s"',
            '        sleep "$backoff"',
            "        backoff=$((backoff * 2))",
            '        [ "$backoff" -gt "$max_backoff" ] && backoff=$max_backoff',
            "    fi",
            "done",
            'log "alive flag removed; supervisor exiting"',
            'rm -f "$PIDFILE"',
            "",
        ]
    )


__all__ = [
    "DEFAULT_BACKOFF_START_SEC",
    "DEFAULT_BACKOFF_MAX_SEC",
    "package_of",
    "runtime_dir",
    "log_path",
    "flag_path",
    "pidfile_path",
    "script_path",
    "build_respawn_script",
]


# EOF
