#!/usr/bin/env python3
# Timestamp: 2026-04-28
# File: scitex_dev/_pypi_package_data.py

"""Audit non-Python data files in src/<pkg>/ vs the built wheel.

A package can have SKILL.md, *.yaml, *.json, *.txt, *.png, etc. sitting
in ``src/<pkg>/`` on disk and committed to git, yet **never ship them on
PyPI**. ``setuptools.packages.find`` and ``hatchling``'s default include
rules pick up Python files (``*.py``) plus directories with
``__init__.py`` — arbitrary data files are silently dropped unless
explicitly declared.

Bug class caught:
- src tree has ``src/scitex_hpc/_skills/scitex-hpc/SKILL.md``
- ``pyproject.toml`` has ``[tool.setuptools.packages.find] where = ["src"]``
- ``python -m build`` produces a wheel that does NOT contain SKILL.md
- ``pip install scitex-hpc`` succeeds but the package can't load its skill

This module:

1. Lists data-file candidates in ``src/<pkg>/`` (anything not ``*.py``,
   ``*.pyc``, ``__pycache__``, or hidden).
2. Builds the wheel (or reads a freshly-built one if provided).
3. Compares: every src data file should appear inside the wheel.
4. Reports missing files + suggests the minimal config snippet to fix.

The fix snippet differs by build backend:
- setuptools: ``[tool.setuptools.package-data]`` glob
- hatchling: ``[tool.hatch.build.targets.wheel] include`` or
  ``packages`` plus ``force-include``

Use as a pre-publish gate. Catches the bug before the wheel is uploaded.
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
import zipfile
from dataclasses import dataclass, field
from pathlib import Path

# File extensions we treat as "data files" worth shipping.
# Hidden files, __pycache__, *.pyc, and *.py are excluded by default.
DATA_EXTENSIONS = {
    ".md",
    ".rst",
    ".txt",
    ".yaml",
    ".yml",
    ".json",
    ".toml",
    ".cfg",
    ".ini",
    ".csv",
    ".tsv",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".svg",
    ".html",
    ".css",
    ".js",
    ".sql",
    ".sh",
}


@dataclass
class PackageDataAuditReport:
    """Result of auditing a package's data-file shipping."""

    package_name: str
    pkg_dir: Path
    src_data_files: list[Path] = field(default_factory=list)
    wheel_path: Path | None = None
    wheel_data_files: list[str] = field(default_factory=list)
    missing_in_wheel: list[Path] = field(default_factory=list)
    build_backend: str = ""
    config_has_package_data: bool = False
    fix_suggestion: str = ""

    @property
    def is_clean(self) -> bool:
        """True if all src data files are shipped in the wheel."""
        return not self.missing_in_wheel

    def summary(self) -> str:
        """One-line summary."""
        if self.is_clean:
            return f"{self.package_name}: ok ({len(self.src_data_files)} data files shipped)"
        return f"{self.package_name}: {len(self.missing_in_wheel)}/{len(self.src_data_files)} data files missing from wheel"


def _list_src_data_files(pkg_root: Path) -> list[Path]:
    """Return data files under ``pkg_root/src/`` worth shipping.

    Skips: __pycache__, *.pyc, *.py, .DS_Store, hidden dirs.
    Filters to known data extensions (see DATA_EXTENSIONS).
    """
    src = pkg_root / "src"
    if not src.is_dir():
        return []
    out: list[Path] = []
    for p in src.rglob("*"):
        if not p.is_file():
            continue
        rel = p.relative_to(src)
        rel_parts = rel.parts
        if "__pycache__" in rel_parts:
            continue
        # Skip metadata generated by setuptools/build, not shipped:
        if any(
            part.endswith(".egg-info") or part.endswith(".dist-info")
            for part in rel_parts
        ):
            continue
        # Skip dot-prefixed components inside the package tree only
        # (filter must not look at the full path — pytest's tmp_path
        # often includes ``.cache`` etc.).
        if any(part.startswith(".") for part in rel_parts):
            continue
        if p.suffix == ".py" or p.suffix == ".pyc":
            continue
        if p.suffix.lower() not in DATA_EXTENSIONS:
            continue
        out.append(rel)
    return sorted(out)


def _detect_backend(pyproject_path: Path) -> str:
    """Return the build-backend name from pyproject.toml, or ''."""
    try:
        text = pyproject_path.read_text()
    except OSError:
        return ""
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("build-backend") and "=" in s:
            value = s.split("=", 1)[1].strip().strip('"').strip("'")
            return value
    return ""


def _has_package_data_block(pyproject_path: Path, backend: str) -> bool:
    """Quick check for a package-data block."""
    try:
        text = pyproject_path.read_text()
    except OSError:
        return False
    if "setuptools" in backend:
        return "[tool.setuptools.package-data]" in text
    if "hatchling" in backend:
        return "[tool.hatch.build.targets.wheel]" in text and (
            "include" in text or "force-include" in text
        )
    return False


def _suggest_fix(backend: str, pkg_import_name: str, missing_globs: list[str]) -> str:
    """Generate the minimal pyproject snippet to ship the missing files."""
    if not missing_globs:
        return ""
    if "setuptools" in backend:
        body = ",\n    ".join(f'"{g}"' for g in missing_globs)
        return (
            f'[tool.setuptools.package-data]\n"{pkg_import_name}" = [\n    {body},\n]'
        )
    if "hatchling" in backend:
        body = ",\n    ".join(f'"src/{pkg_import_name}/{g}"' for g in missing_globs)
        return f"[tool.hatch.build.targets.wheel.force-include]\n" + "\n".join(
            f'"src/{pkg_import_name}/{g}" = "{pkg_import_name}/{g}"'
            for g in missing_globs
        )
    return f"# Unknown backend {backend}; declare {missing_globs} per backend docs."


def _build_wheel(pkg_root: Path) -> Path:
    """Build a wheel into a tmp dir and return its path."""
    out = Path(tempfile.mkdtemp(prefix="scitex-pkg-data-audit-"))
    subprocess.run(
        ["python", "-m", "build", "--wheel", "--outdir", str(out)],
        cwd=pkg_root,
        check=True,
        capture_output=True,
    )
    wheels = sorted(out.glob("*.whl"))
    if not wheels:
        raise RuntimeError(f"build produced no wheel under {out}")
    return wheels[-1]


def _list_wheel_files(wheel_path: Path) -> list[str]:
    """Return all member paths inside a wheel."""
    with zipfile.ZipFile(wheel_path) as z:
        return z.namelist()


def audit_package_data(
    pkg_root: Path,
    *,
    pkg_import_name: str | None = None,
    wheel_path: Path | None = None,
    keep_wheel: bool = False,
) -> PackageDataAuditReport:
    """Check that every data file in ``src/`` is shipped in the wheel.

    Parameters
    ----------
    pkg_root : Path
        The package directory (contains ``pyproject.toml`` and ``src/``).
    pkg_import_name : str | None
        Override the import name (e.g. ``scitex_io``). Default: detect
        from the single subdir under ``src/``.
    wheel_path : Path | None
        Use an existing wheel instead of building. Default: build one.
    keep_wheel : bool
        If True, don't delete the temp-built wheel after the audit.

    Returns
    -------
    PackageDataAuditReport
    """
    pkg_root = pkg_root.resolve()
    pyproject = pkg_root / "pyproject.toml"
    backend = _detect_backend(pyproject)

    src = pkg_root / "src"
    if pkg_import_name is None:
        candidates = (
            [d for d in src.iterdir() if d.is_dir() and (d / "__init__.py").exists()]
            if src.is_dir()
            else []
        )
        if len(candidates) == 1:
            pkg_import_name = candidates[0].name
        else:
            pkg_import_name = pkg_root.name.replace("-", "_")

    src_data = _list_src_data_files(pkg_root)
    has_data_cfg = _has_package_data_block(pyproject, backend)

    built_here = False
    if wheel_path is None:
        wheel_path = _build_wheel(pkg_root)
        built_here = True
    try:
        wheel_files = _list_wheel_files(wheel_path)
    finally:
        if built_here and not keep_wheel:
            shutil.rmtree(wheel_path.parent, ignore_errors=True)

    # Wheel paths look like "<pkg>/<rel>" (no "src/" prefix).
    wheel_data = sorted(
        f
        for f in wheel_files
        if not f.endswith(".py")
        and not f.startswith(f"{pkg_import_name}-")  # dist-info
        and Path(f).suffix.lower() in DATA_EXTENSIONS
    )

    # Compare: src_data paths are already relative to src/ (and include the
    # pkg dir), wheel paths are also relative to wheel root (and include the
    # pkg dir). Direct set-difference.
    expected_in_wheel = {rel.as_posix() for rel in src_data}
    actually_in_wheel = set(wheel_data)
    missing_paths = sorted(expected_in_wheel - actually_in_wheel)
    missing_rels = [Path(p) for p in missing_paths]

    fix = _suggest_fix(
        backend,
        pkg_import_name,
        [str(rel) for rel in missing_rels],
    )

    return PackageDataAuditReport(
        package_name=pkg_root.name,
        pkg_dir=pkg_root,
        src_data_files=src_data,
        wheel_path=wheel_path if not built_here or keep_wheel else None,
        wheel_data_files=wheel_data,
        missing_in_wheel=missing_rels,
        build_backend=backend,
        config_has_package_data=has_data_cfg,
        fix_suggestion=fix,
    )


# EOF
