"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil

import pytest


# audit-all fans out to 6 sub-auditor subprocesses (audit-cli,
# audit-mcp-tools, audit-skills, audit-python-apis, audit-project,
# audit-django), each re-importing the package fresh; on a loaded or
# NFS-backed host this legitimately runs well past this repo's global
# [tool.pytest.ini_options] `timeout` default even when the audit itself
# is completely clean. Override per-test rather than raise the global
# cap for every other (fast) test.
@pytest.mark.timeout(600)
def test_audit_all_clean():
    # Arrange
    # Act
    # Assert
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    audit_all_for_package('scitex-dev')
