"""Audit conformance — runs `scitex-dev ecosystem audit-all`
on this package as a normal test. Generated by
`scitex-dev ecosystem install-audit-gate`. Re-run that command
after upgrading scitex-dev to refresh any pin in [dev].

Bypass (exceptions / temporal remedy):
    SCITEX_DEV_SKIP_AUDIT=1 python -m pytest .

Use when remediating pre-existing violations or developing
without the audit corpus available locally. CI for release
branches MUST NOT set this — drift goes silent.
"""

import shutil
from pathlib import Path

import pytest


# audit-all fans out to 6 sub-auditor subprocesses (audit-cli,
# audit-mcp-tools, audit-skills, audit-python-apis, audit-project,
# audit-django), each re-importing the package fresh; on a loaded or
# NFS-backed host this legitimately runs well past this repo's global
# [tool.pytest.ini_options] `timeout` default even when the audit itself
# is completely clean. Override per-test rather than raise the global
# cap for every other (fast) test.
@pytest.mark.timeout(600)
def test_audit_all_clean():
    # Arrange
    # Act
    # Assert
    if shutil.which("scitex-dev") is None:
        pytest.skip(
            "scitex-dev not installed — add `scitex-dev[cli-audit]` "
            "to [project.optional-dependencies.dev]"
        )
    from scitex_dev.testing import audit_all_for_package

    # Anchor the audit on THIS checkout (the tree pytest is running against),
    # threaded through as `--path`. Without it, audit-all falls back to a
    # resolve-by-name `~/proj/<pkg>` development guess; on the shared
    # self-hosted (Spartan pooled) runner that guess resolves the operator's
    # `/home/ywatanabe/proj/scitex-dev` develop checkout — a DIFFERENT tree
    # and commit than the one under test — so the gate graded stale source
    # (the resolved-tree banner from PR #392 surfaced exactly this). The file
    # lives at <root>/tests/develop/test_audit.py, so parents[2] is the root.
    audit_all_for_package('scitex-dev', path=Path(__file__).resolve().parents[2])
