"""Baseline ratchet for audit-cli (slice 4 of the CLI-standardization plan).

Lets a repo adopt the auditor incrementally: record today's violations
once, then fail/warn only on NEW ones. The baseline file is
``.scitex/dev/cli-audit-baseline.yaml`` (relative to the cwd) unless
``--baseline PATH`` names another file.

Semantics (see ``run_audit`` / ``run_audit_all``):

- ``--baseline`` given and the file MISSING → the run reports normally,
  then writes every current violation fingerprint to the file and exits
  0 (ratchet initialization).
- Baseline file PRESENT (flag or not — the file's existence opts in) →
  previously-recorded violations are suppressed (a count is shown) and
  only new violations fail/warn. To re-record, delete the file and pass
  ``--baseline`` again.

Fingerprints are stable keys: ``<rule>|<command path>|<message-invariant>``
where the message-invariant part replaces every digit run with ``N``
(counts, timings and versions churn between runs), collapses whitespace,
and truncates to 160 chars (trailing sample lists churn too).
"""

from __future__ import annotations

import re
from pathlib import Path

import yaml

__all__ = [
    "DEFAULT_BASELINE_RELPATH",
    "fingerprint_violation",
    "load_baseline",
    "partition_violations",
    "resolve_baseline_path",
    "write_baseline",
]

DEFAULT_BASELINE_RELPATH = Path(".scitex") / "dev" / "cli-audit-baseline.yaml"

_BASELINE_VERSION = 1
_INVARIANT_MAX_CHARS = 160


def resolve_baseline_path(baseline_path: str | Path | None) -> Path:
    """The baseline file to use: explicit path or the cwd default."""
    if baseline_path:
        return Path(baseline_path).expanduser()
    return Path.cwd() / DEFAULT_BASELINE_RELPATH


def fingerprint_violation(violation) -> str:
    """Stable key for one violation: rule + command path + message-invariant."""
    invariant = re.sub(r"\d+", "N", violation.message)
    invariant = re.sub(r"\s+", " ", invariant).strip()[:_INVARIANT_MAX_CHARS]
    return f"{violation.rule}|{violation.command}|{invariant}"


def load_baseline(path: Path) -> set[str]:
    """Read the fingerprint set from a baseline file.

    A malformed file raises (no silent fallback — a corrupt baseline
    silently suppressing nothing OR everything would be undebuggable).
    """
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(data, dict) or not isinstance(
        data.get("fingerprints", []), list
    ):
        raise ValueError(
            f"malformed cli-audit baseline at {path}: expected a mapping "
            f"with a `fingerprints:` list — delete and re-record with "
            f"--baseline"
        )
    return {str(fp) for fp in data.get("fingerprints", [])}


def write_baseline(path: Path, violations: list) -> int:
    """Record every violation's fingerprint; returns the count written."""
    fingerprints = sorted({fingerprint_violation(v) for v in violations})
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "version": _BASELINE_VERSION,
        "fingerprints": fingerprints,
    }
    header = (
        "# cli-audit baseline — ratchet file (generated by "
        "`scitex-dev ecosystem audit-cli --baseline`).\n"
        "# Recorded violations are suppressed; only NEW violations "
        "fail/warn.\n"
        "# To re-record: delete this file and re-run with --baseline.\n"
    )
    path.write_text(
        header + yaml.safe_dump(payload, sort_keys=True), encoding="utf-8"
    )
    return len(fingerprints)


def partition_violations(
    violations: list, baseline: set[str]
) -> tuple[list, list]:
    """Split into (new, suppressed) against a baseline fingerprint set."""
    new: list = []
    suppressed: list = []
    for violation in violations:
        if fingerprint_violation(violation) in baseline:
            suppressed.append(violation)
        else:
            new.append(violation)
    return new, suppressed
