#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate ``~/.ssh`` stanzas from the host registry.

One registry, one generator, two names per host: the BARE canonical name for
the LAN route and ``<name>-net`` for the route that leaves the LAN. The
generator can emit a bastion/jump ONLY under the ``-net`` name, because the
LAN side of :class:`~._connectivity.HostConnectivity` has no field that could
hold one. That is the operator's 2026-08-13 naming rule expressed as code
rather than as a comment.

WHAT THIS WILL NOT DO
---------------------
**It never deletes a host because the host is unreachable.** Operator rule:
unreachable != delete. An entry whose machine is off ages — its ``last_seen``
stops advancing and the generator renders that age into the stanza comment —
and it keeps its name. Deleting on failure would mean a laptop closed for a
weekend silently loses its route, and the registry would then be describing
the reachability of the moment rather than the shape of the fleet.

**It never touches anything outside its managed block.** The block is
delimited by :data:`BEGIN_MARKER` / :data:`END_MARKER`; :func:`write_managed`
replaces exactly that region and nothing else. If it finds one marker without
its partner it REFUSES rather than guessing where the region ends — guessing
there would delete hand-written stanzas, which is a worse outcome than not
running.

THE ORDERING HAZARD, WHICH GENERATION ALONE DOES NOT FIX
--------------------------------------------------------
ssh takes the FIRST obtained value for each keyword, so an earlier stanza
wins over a later one and an ``Include`` is expanded in place. Measured
2026-08-13: ``~/.ssh/config`` began with ``Include conf.d/*/*.conf``, so an
included file silently beat every stanza below it and the file people were
reading was not the file ssh was obeying. Writing a correct block is
therefore only half a guarantee; :mod:`._effective` asks ``ssh -G`` what
actually won, and that is the half that catches this.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .._core.errors import ErrorCode
from ._connectivity import net_name

__all__ = [
    "BEGIN_MARKER",
    "END_MARKER",
    "ManagedWrite",
    "default_managed_path",
    "render_ssh_config",
    "write_managed",
]

BEGIN_MARKER = "# >>> scitex-dev host registry: BEGIN managed block >>>"
END_MARKER = "# <<< scitex-dev host registry: END managed block <<<"

_HEADER_NOTE = """\
# Generated by `scitex-dev host generate-ssh-config` from the SciTeX host registry.
# Edits INSIDE this block are overwritten on the next run; edits outside it
# are never touched.
#
# TWO NAMES PER HOST, and the distinction is load-bearing:
#   <name>       LAN route      — direct address, no bastion, ever.
#   <name>-net   off-LAN route  — Cloudflare / reverse SSH. ONLY here.
#
# ORDERING: ssh takes the FIRST value it obtains for each keyword, and an
# `Include` is expanded where it appears. If this block sits BELOW an
# `Include` that also defines these hosts, the included file wins and this
# one is inert. Verify with `scitex-dev host validate-ssh-config`, which asks
# `ssh -G` what actually won rather than assuming this file did.
#
# An entry is never removed because its machine is unreachable. `last_seen`
# below records when the address was last observed — read it as the age of
# the claim, not as a promise about right now."""


def default_managed_path() -> Path:
    """The conventional destination for the managed block.

    A file of its OWN under ``~/.ssh/conf.d/`` rather than an appended region
    of ``~/.ssh/config``, so a mistake here can never damage hand-written
    configuration. It still has to be reached by an ``Include``, and this
    function deliberately does not add one: editing the top of someone's ssh
    config to change which stanzas win is precisely the change that caused
    the incident this module exists to prevent.
    """
    return Path.home() / ".ssh" / "conf.d" / "scitex-dev-hosts.conf"


def _stanza(alias: str, lines: list[tuple[str, str]], comments: list[str]) -> list[str]:
    out = [f"Host {alias}"]
    out.extend(f"    # {c}" for c in comments)
    out.extend(f"    {key} {value}" for key, value in lines)
    return out


def _lan_stanza(record) -> list[str] | None:
    """The BARE-name stanza. LAN only — structurally cannot carry a bastion."""
    conn = record.connectivity
    if not conn.lan:
        return None
    lines: list[tuple[str, str]] = [("HostName", conn.lan)]
    if conn.ssh_user:
        lines.append(("User", conn.ssh_user))
    if conn.identity_file:
        lines.append(("IdentityFile", conn.identity_file))
        # `IdentitiesOnly yes` is emitted TOGETHER with IdentityFile and never
        # alone: it tells ssh to offer only the named key. Without it an agent
        # holding many keys offers them in its own order and can exhaust the
        # server's MaxAuthTries before reaching the right one — which fails as
        # "Permission denied", indistinguishable from the key being wrong.
        lines.append(("IdentitiesOnly", "yes"))
    comments = ["LAN route (no bastion — see the naming rule above)"]
    if conn.last_seen:
        comments.append(f"last_seen: {conn.last_seen}")
    if conn.reserved and conn.reserved != conn.lan:
        # Both facts are true and they disagree; say so where the route is
        # read. A reader who sees only the observed address cannot tell a
        # deliberate static address from an unrenewed lease.
        comments.append(
            f"DHCP reservation is {conn.reserved} — observed at {conn.lan} "
            "(lease not renewed)"
        )
    if conn.host_key_fingerprint:
        comments.append(f"host key: {conn.host_key_fingerprint}")
    return _stanza(record.name, lines, comments)


def _net_stanza(record) -> list[str] | None:
    """The ``-net`` stanza. The ONLY place a bastion/jump/proxy may appear."""
    route = record.connectivity.net
    if route is None:
        return None
    lines: list[tuple[str, str]] = []
    if route.hostname:
        lines.append(("HostName", route.hostname))
    if route.port:
        lines.append(("Port", str(route.port)))
    if record.connectivity.ssh_user:
        lines.append(("User", record.connectivity.ssh_user))
    if record.connectivity.identity_file:
        lines.append(("IdentityFile", record.connectivity.identity_file))
        lines.append(("IdentitiesOnly", "yes"))
    if route.proxy_command:
        lines.append(("ProxyCommand", route.proxy_command))
    elif route.transport == "cloudflared":
        lines.append(("ProxyCommand", "cloudflared access ssh --hostname %h"))
    elif route.transport == "reverse-ssh":
        lines.append(("ProxyJump", route.jump or ""))
    comments = [f"off-LAN route via {route.transport}"]
    if record.connectivity.last_seen:
        comments.append(f"last_seen: {record.connectivity.last_seen}")
    return _stanza(net_name(record.name), lines, comments)


def render_ssh_config(records, *, source: str | Path | None = None) -> str:
    """Render the managed block for ``records``, markers included.

    Pure: same registry in, same text out, so writing it twice changes
    nothing. ``source`` (the registry path) is recorded as a comment for the
    human who finds this file later and wants to know what generates it — a
    TIMESTAMP is deliberately NOT recorded, because a header that changes on
    every run makes every run look like a change and destroys the one signal
    :func:`write_managed` reports.

    A host with no ``lan`` and no ``net`` contributes NOTHING — not an empty
    stanza. A ``Host`` block with no ``HostName`` silently resolves to the
    alias itself, which is how a name ends up connecting to whatever DNS
    happens to answer for it.
    """
    lines: list[str] = [BEGIN_MARKER, _HEADER_NOTE]
    if source is not None:
        lines.append(f"# source: {source}")
    lines.append("")
    emitted = 0
    for record in records:
        for stanza in (_lan_stanza(record), _net_stanza(record)):
            if stanza is None:
                continue
            lines.extend(stanza)
            lines.append("")
            emitted += 1
    if emitted == 0:
        # Say it rather than emitting a blank region. An empty managed block
        # and a correct one look identical in a diff of a file nobody reads;
        # the sentence is what tells a reader the registry has no addresses,
        # not that the generator failed.
        lines.append("# (no host in the registry records a `lan` or a `net` route)")
        lines.append("")
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


@dataclass(frozen=True)
class ManagedWrite:
    """What :func:`write_managed` did.

    ``changed`` is the field to act on: ``False`` means the file already held
    exactly this block, which is the idempotence contract stated as data
    rather than inferred from silence.
    """

    path: Path
    created: bool
    changed: bool
    bytes_written: int
    #: True when nothing was actually written. The other fields still describe
    #: what WOULD have happened, which is the whole point: a dry run that
    #: reported nothing would be indistinguishable from a no-op.
    dry_run: bool = False

    @property
    def state(self) -> str:
        """``created`` / ``updated`` / ``unchanged`` — one word for a report."""
        if not self.changed:
            return "unchanged"
        return "created" if self.created else "updated"

    def to_dict(self) -> dict[str, object]:
        return {
            "path": str(self.path),
            "created": self.created,
            "changed": self.changed,
            "bytes_written": self.bytes_written,
            "dry_run": self.dry_run,
            "state": self.state,
        }


def _split_around_block(text: str, path: Path) -> tuple[str, str]:
    """Return the text BEFORE and AFTER the managed block.

    Refuses on a half-present block. One marker without its partner means the
    region's extent is unknown, and every way of guessing it ends in deleting
    lines this program did not write.
    """
    from ._registry import HostRegistryError

    has_begin = BEGIN_MARKER in text
    has_end = END_MARKER in text
    if has_begin != has_end:
        missing = END_MARKER if has_begin else BEGIN_MARKER
        raise HostRegistryError(
            f"{path}: the managed block is half-present — found one marker "
            f"but not its partner. Refusing to write: the region's extent is "
            f"unknown, and every way of guessing it risks deleting lines this "
            f"generator did not write.",
            code=ErrorCode.CONFLICT,
            remediation=(
                f"Either restore the missing marker line\n    {missing}\n"
                "or delete the remaining one, and re-run."
            ),
        )
    if not has_begin:
        return text, ""
    before, _, rest = text.partition(BEGIN_MARKER)
    _, _, after = rest.partition(END_MARKER)
    if after.startswith("\n"):
        after = after[1:]
    return before, after


def write_managed(
    path: str | Path, block: str, *, dry_run: bool = False
) -> ManagedWrite:
    """Write ``block`` into ``path``'s managed region, leaving the rest alone.

    Three cases, all idempotent:

    * file absent -> created holding only the block (mode ``0600``);
    * block present -> that region and ONLY that region is replaced;
    * file present without the block -> the block is APPENDED, and every
      existing line is preserved byte for byte.

    Never removes a stanza outside the markers, and never removes a host from
    inside them for being unreachable — see the module docstring.

    ``dry_run`` computes the whole outcome — including the half-present-block
    REFUSAL, which is the one a caller most needs to learn before committing —
    and returns it without touching the filesystem. The refusal is raised
    during a dry run on purpose: a preview that quietly succeeded where the
    real run will fail is worse than no preview.
    """
    target = Path(path).expanduser()
    existing = target.read_text() if target.is_file() else None
    created = existing is None

    if existing is None:
        new_text = block
    else:
        before, after = _split_around_block(existing, target)
        if BEGIN_MARKER in existing:
            new_text = before + block + after
        else:
            separator = "" if not existing or existing.endswith("\n") else "\n"
            new_text = existing + separator + "\n" + block

    if existing == new_text:
        return ManagedWrite(
            target, created=False, changed=False, bytes_written=0, dry_run=dry_run
        )

    if dry_run:
        return ManagedWrite(
            target,
            created=created,
            changed=True,
            bytes_written=len(new_text),
            dry_run=True,
        )

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(new_text)
    # ssh REFUSES a user config that is group/world readable, so a generator
    # that writes 0644 produces a file ssh will not read — a failure that
    # surfaces as "my stanza is being ignored", i.e. as this module's own bug.
    target.chmod(0o600)
    return ManagedWrite(
        target, created=created, changed=True, bytes_written=len(new_text)
    )


# EOF
